### PR TITLE
Multiple connections

### PR DESCRIPTION
**Pull request by marshallswain**
Allows multiple connections to be made.  Includes #12.

### CODE REVIEW

**Comment by ilyavf** [comment]
@marshallswain The parameter `forceNew` is not defined for `socket.io`, is it? If its not, then we probably need to do something else. I think we have to mimic what `socket.io` is doing in the same case, and don't add our own custom param.

**Comment by marshallswain** [comment]
@ilyavf Yes, `forceNew` is a socket.io param.

**Comment by ilyavf** [comment]
Yeah, you are right, it is, I just didnt find it in docs.
There is also an alias called `"force new connection"`.

**Comment by marshallswain** [comment]
@ilyavf do you know if the `meta` config is still needed in the `package.json`?  I think it is left over from before they changed the socket.io-client folder structure.

**Comment by marshallswain** [comment]
When we continue work on this:

The delayIO module should duplicate the functionality of socket.io library, which creates an internal manager for each call to io(‘’) with a unique URL.  Right now we are not allowing it to create all managers.  Only the default manager is in place.

**Comment by marshallswain** [comment]
@ilyavf once we get https://github.com/canjs/can-fixture-socket/issues/13 completed, we can update the dependency here: https://github.com/stealjs/steal-socket.io/pull/13/commits/344e3960412e32e75af3fe44bb061b6981905fdf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29

**Pull request merged**
