### PR TITLE
Upgrade socket.io-client v2

### PR DESCRIPTION
**Pull request by frank-dspeed**
Fully tested verifyed:
QUnit 1.23.1; Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

Tests completed in 103 milliseconds.
24 assertions of 24 passed, 0 failed.

### CODE REVIEW

**Comment by frank-dspeed** [comment]
closes: https://github.com/stealjs/steal-socket.io/issues/26

**Comment by frank-dspeed** [comment]
@matthewp bump this up for 4.0 so i can remove my branch

**Comment by matthewp** [comment]
Will put this in donejs 2.0, thanks!

**Comment by matthewp** [comment]
Sorry for the delay, thanks @frank-dspeed !

**Pull request merged**
